### PR TITLE
Mining and Oil Change

### PR DESCRIPTION
**Pull request by Hedrauta**
With this change, it will shown as "total veins covered" and "total per Sec" at Oil, which can be better handled as it is currently
does work perfectly... tested it locally

### CODE REVIEW

**Comment by ShadowTheAge** [comment]
I am using a script to generate data.json
If you'd like to describe how these changes were made, I can add these to the script

**Comment by Hedrauta** [comment]
i changed the name "Mining Machines" to "total covered" and the the mining-speed to 0.5
`{"category":"category-buildings",
"id":"i2301","name":"total veins covered","row":3,"stack":20,"factory":{"drain":0,"electric":0,"mining":true,"speed":0.5},"fuel":0}`

 and the "Oil Extractor" to "total per sec" 
 `{"category":"category-buildings",
"id":"i2307","name":"total per sec","row":3,"stack":10,"factory":{"drain":0,"electric":0,"mining":true,"speed":1}`
 

it will loook like this:
image
image

the calculation is correct... 
I will change my pull, so its set there, and you just can grab it ;)

**Comment by ShadowTheAge** [comment]
Have you checked how the mining speed works with different minerals?
Because there is a "mining time" property for those and this mining time is different for different minerals. For example it is 1 for iron and 1.5 for titanium.
I don't know if that is actual property or some ignored leftover value.

I will not change the names of the buildings because you can craft buildings separately and I want the names to be correct there.

Is the calculation currently 2 times off for iron?

**Comment by Hedrauta** [comment]
well ..... it is wrong for every ore.... 

At 0% mining speed, it should take 20 total iron ore veins to get 600ores/min (10ores/sec) ... 

At the current build, it says "10 | Ore Vein | Mining Machine" which is completely incorrect.... 
it "may" be kind of correct, if the calculated value will display as "Ores per Sec".... but unfortunately is wrong too... because at 10% mining speed, I would need less "ore per sec" which is wrong thinking... 

So, changing it to "veins covered" at 0.5 rate, will display the correct value at a specific ore/sec

**Comment by Hedrauta** [comment]
That's why I left the ores timing untouched and changed the mining speed timer ;)

**Comment by ShadowTheAge** [comment]
Well, I have did tests right now and looks like that speed is affecting anything. So the actual speed is 0.5/s plus bonus speed, regardless of the mineral.

OK, I am going to update scripts to reflect that

**Comment by ShadowTheAge** [comment]
Should be done

**Pull request closed without merging**
